In [ ]:
import numpy as np 
import torch 
import tensorflow as tf
# import các thư viện cần dùng

Câu 1: Hãy viết chương trình tạo Numpy 2 array, Pytorch tensor với từ list 1 có giá trị [1, 2, 3], list 2 có giá trị [4, 5, 6]. Sau đó sử dụng hàm hstack để nối theo trục ngang và vstack để nối theo trục dọc?

* Numpy 

In [ ]:
np_arr_1 = np.array(np.arange(1,4))
# tạo array từ 1 -> 3
np_arr_2 = np.array(np.arange(4,7))
# tạo array từ 4 -> 6
np_arr_ngang = np.hstack((np_arr_1,np_arr_2))
# hstack giúp nối ngang 2 array 1 chiều
np_arr_doc = np.vstack((np_arr_1,np_arr_2))
# vstack giúp nối dọc 2 array 1 chiều
print(f"{np_arr_ngang} là mảng cuối cùng sau khi nối ngang ")
print()
print(f"{np_arr_doc} là mảng cuối cùng sau khi nối dọc ")
# in kết quả

[1 2 3 4 5 6] là mảng cuối cùng sau khi nối ngang 

[[1 2 3]
 [4 5 6]] là mảng cuối cùng sau khi nối dọc 


* Pytorch 


In [ ]:
torch_arr_1 = torch.tensor(torch.arange(1,4))
# tạo tensor từ 1 -> 3
torch_arr_2 = torch.tensor(torch.arange(4,7))
# tạo tensor từ 4 -> 6
torch_arr_ngang = torch.hstack((torch_arr_1,torch_arr_2))
# hstack giúp nối ngang 2 tensor 1 chiều
torch_arr_doc = torch.vstack((torch_arr_1,torch_arr_2))
# vstack giúp nối dọc 2 tensor 1 chiều
print(f"{torch_arr_ngang} là mảng cuối cùng sau khi nối ngang ")
print()
print(f"{torch_arr_doc} là mảng cuối cùng sau khi nối dọc ")
# in kết quả

tensor([1, 2, 3, 4, 5, 6]) là mảng cuối cùng sau khi nối ngang 

tensor([[1, 2, 3],
        [4, 5, 6]]) là mảng cuối cùng sau khi nối dọc 


C:\Users\ldraw\AppData\Local\Temp\ipykernel_4188\1212474223.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch_arr_1 = torch.tensor(torch.arange(1,4))
C:\Users\ldraw\AppData\Local\Temp\ipykernel_4188\1212474223.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch_arr_2 = torch.tensor(torch.arange(4,7))


Câu 2: Hãy viết chương trình tạo Numpy 2 array, Pytorch tensor, Tensorflow tensor từ list 2D là [[1 , 2 , 3] , [4 , 5 , 6]] và [[7 , 8 , 9] , [10 , 11 , 12]]. Sau đó sử dụng hàm concanate để nối theo trục ngang và vstack để nối theo trục dọc?

* Numpy 

In [17]:
np_arr_2D_1 = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
# khởi tạo array 2D thứ nhất theo đề bài
np_arr_2D_2 = np.array([[7 , 8 , 9] , [10 , 11 , 12]])
# khởi tạo array 2D thứ hai theo đề bài
np_arr_2D_ngang = np.concatenate((np_arr_2D_1,np_arr_2D_2),axis =1)
# concanate giúp nối ngang 2 mảng 2D
np_arr_2D_doc = np.vstack((np_arr_2D_1,np_arr_2D_2))
# vstack giúp nối dọc 2 mảng 2D
print(f"{np_arr_2D_ngang} là mảng cuối cùng sau khi nối ngang ")
print()
print(f"{np_arr_2D_doc} là mảng cuối cùng sau khi nối dọc ")
# in kết quả

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] là mảng cuối cùng sau khi nối ngang 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] là mảng cuối cùng sau khi nối dọc 


* Pytorch 

In [18]:
torch_arr_2D_1 = torch.tensor([[1 , 2 , 3] , [4 , 5 , 6]])
# khởi tạo tensor 2D thứ nhất theo đề bài
torch_arr_2D_2 = torch.tensor([[7 , 8 , 9] , [10 , 11 , 12]])
# khởi tạo array 2D thứ hai theo đề bài
torch_arr_2D_ngang = torch.cat((torch_arr_2D_1,torch_arr_2D_2),axis =1)
# cat giúp nối ngang 2 tensor 2D
torch_arr_2D_doc = torch.vstack((torch_arr_2D_1,torch_arr_2D_2))
# vstack giúp nối dọc 2 tensor 2D
print(f"{torch_arr_2D_ngang} là mảng cuối cùng sau khi nối ngang ")
print()
print(f"{torch_arr_2D_doc} là mảng cuối cùng sau khi nối dọc ")
# in kết quả

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]) là mảng cuối cùng sau khi nối ngang 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) là mảng cuối cùng sau khi nối dọc 


* Tensorflow 

In [ ]:
tf_arr_2D_1 = tf.convert_to_tensor([[1 , 2 , 3] , [4 , 5 , 6]])
# khởi tạo tensor 2D thứ nhất theo đề bài
tf_arr_2D_2 = tf.convert_to_tensor([[7 , 8 , 9] , [10 , 11 , 12]])
# khởi tạo array 2D thứ hai theo đề bài
tf_arr_2D_ngang = tf.concat((tf_arr_2D_1,tf_arr_2D_2),axis = 1)
tf_arr_2D_doc = tf.concat((tf_arr_2D_1,tf_arr_2D_2),axis = 0)
# concat giúp nối 2 tensor với nhau
# axis = 1 để nối theo chiều ngang
# axis = 2 để nối theo chiều dọc
print(f"{tf_arr_2D_ngang} là mảng cuối cùng sau khi nối ngang ")
print()
print(f"{tf_arr_2D_doc} là mảng cuối cùng sau khi nối dọc ")
# in kết quả

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] là mảng cuối cùng sau khi nối ngang 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] là mảng cuối cùng sau khi nối dọc 
