In [1]:
import numpy as np 
import torch
import tensorflow as tf
#import các thư viện cần dùng

Câu 1: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2 và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

* Numpy 

In [15]:
np.random.seed(2024)
np_arr_1 = np.random.randint(-10,10,size=(3,4))
# khởi tạo ma trận 1 bằng numpy theo đề bài
np_arr_2 = np.random.randint(-10,10,size=(3,4))
# khởi tạo ma trậng 2 bằng numpy theo đề bài
np_arr_2 = np.transpose(np_arr_2)
# chuyển vị ma trận 3x4 sang 4x3 để nhân ma trận
np_arr_tich = []
# khởi tạo biến lưu kết quả tích ma trận 1 và 2
for i in range(0,3):
    row_i = []
    # khởi tạo dòng i để lưu từng phần tử
    for j in range(0,3):
        element_ik = 0
        # khởi tạo từng phần tử trong dòng i
        for k in range(0,4):
            element_ik += np_arr_1[i][k]*np_arr_2[k][j]
            # cộng dồn để tạo ra từng phần tử trong dòng i
        row_i.append(element_ik)
        # sau khi phần tử cộng dồn xong thì cho vào dòng i
    np_arr_tich.append(row_i)
    # cho dòng i vào mảng 
print(np_arr_tich)
# in kết quả

[[np.int32(-80), np.int32(-46), np.int32(128)], [np.int32(-33), np.int32(-30), np.int32(67)], [np.int32(-25), np.int32(-25), np.int32(42)]]


* Pytorch 

In [14]:
torch.manual_seed(2024)
torch_arr_1 = torch.randint(-10,10,size=(3,4))
# khởi tạo ma trận 1 bằng pytorch theo đề bài
torch_arr_2 = torch.randint(-10,10,size=(3,4))
# khởi tạo ma trậng 2 bằng pytorch theo đề bài
torch_arr_2 = torch.transpose(torch_arr_2,0,1)
# chuyển vị ma trận 3x4 sang 4x3 để nhân ma trận
torch_arr_tich = []
# khởi tạo biến lưu kết quả tích ma trận 1 và 2
for i in range(0,3):
    row_i = []
    # khởi tạo dòng i để lưu từng phần tử
    for j in range(0,3):
        element_ik = 0
        # khởi tạo từng phần tử trong dòng i
        for k in range(0,4):
            element_ik += torch_arr_1[i][k]*torch_arr_2[k][j]
            # cộng dồn để tạo ra từng phần tử trong dòng i
        row_i.append(element_ik)
        # sau khi phần tử cộng dồn xong thì cho vào dòng i
    torch_arr_tich.append(row_i)
    # cho dòng i vào mảng 
print(torch_arr_tich)
# in kết quả

[[tensor(22), tensor(36), tensor(-62)], [tensor(-89), tensor(163), tensor(99)], [tensor(87), tensor(-180), tensor(-148)]]


* Tensorflow 

In [16]:
tf.random.set_seed(2024)
tf_arr_1 = tf.random.uniform((3,4),minval =-10,maxval=10)
# khởi tạo ma trận 1 bằng pytorch theo đề bài
tf_arr_2 = tf.random.uniform((3,4),minval =-10,maxval=10)
# khởi tạo ma trậng 2 bằng pytorch theo đề bài
tf_arr_2 = tf.transpose(tf_arr_2)
# chuyển vị ma trận 3x4 sang 4x3 để nhân ma trận
tf_arr_tich = []
# khởi tạo biến lưu kết quả tích ma trận 1 và 2
for i in range(0,3):
    row_i = []
    # khởi tạo dòng i để lưu từng phần tử
    for j in range(0,3):
        element_ik = 0
        # khởi tạo từng phần tử trong dòng i
        for k in range(0,4):
            element_ik += tf_arr_1[i][k]*tf_arr_2[k][j]
            # cộng dồn để tạo ra từng phần tử trong dòng i
        row_i.append(element_ik)
        # sau khi phần tử cộng dồn xong thì cho vào dòng i
    tf_arr_tich.append(row_i)
    # cho dòng i vào mảng 
print(tf_arr_tich)
# in kết quả

[[<tf.Tensor: shape=(), dtype=float32, numpy=-36.226318359375>, <tf.Tensor: shape=(), dtype=float32, numpy=-17.063106536865234>, <tf.Tensor: shape=(), dtype=float32, numpy=-62.29872131347656>], [<tf.Tensor: shape=(), dtype=float32, numpy=21.901601791381836>, <tf.Tensor: shape=(), dtype=float32, numpy=-9.12588882446289>, <tf.Tensor: shape=(), dtype=float32, numpy=61.55303192138672>], [<tf.Tensor: shape=(), dtype=float32, numpy=21.210763931274414>, <tf.Tensor: shape=(), dtype=float32, numpy=-70.0738296508789>, <tf.Tensor: shape=(), dtype=float32, numpy=74.90974426269531>]]


Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

* Numpy :

In [2]:
np.random.seed(2024)
np_arr = np.random.randint(-10,10,size=(3,3))
# khởi tạo ma trận 1 bằng numpy theo đề bài
print(f"Tổng tất cả phần tử trong mảng là: {np.sum(np_arr)}")
print()
print(f"Tổng theo chiều dọc của mảng là: {np.sum(np_arr,axis=0)}")
print()
print(f"Tổng theo chiều ngang của mảng là: {np.sum(np_arr,axis=1)}")

Tổng tất cả phần tử trong mảng là: -53

Tổng theo chiều dọc của mảng là: [-15 -11 -27]

Tổng theo chiều ngang của mảng là: [-22 -16 -15]


* Pytorch

In [4]:
torch.manual_seed(2024)
torch_arr = torch.randint(-10,10,size=(3,3))
# khởi tạo ma trận 1 bằng numpy theo đề bài
print(f"Tổng tất cả phần tử trong mảng là: {torch.sum(torch_arr)}")
print()
print(f"Tổng theo chiều dọc của mảng là: {torch.sum(torch_arr,axis=0)}")
print()
print(f"Tổng theo chiều ngang của mảng là: {torch.sum(torch_arr,axis=1)}")

Tổng tất cả phần tử trong mảng là: -27

Tổng theo chiều dọc của mảng là: tensor([ -8,  -6, -13])

Tổng theo chiều ngang của mảng là: tensor([ -4, -27,   4])


* Tensorflow

In [7]:
tf.random.set_seed(2024)
tf_arr = tf.random.uniform((3,3),minval =-10,maxval =10)
# khởi tạo ma trận 1 bằng numpy theo đề bài
print(f"Tổng tất cả phần tử trong mảng là: {tf.reduce_sum(tf_arr)}")
print()
print(f"Tổng theo chiều dọc của mảng là: {tf.reduce_sum(tf_arr,axis=0)}")
print()
print(f"Tổng theo chiều ngang của mảng là: {tf.reduce_sum(tf_arr,axis=1)}")

Tổng tất cả phần tử trong mảng là: -9.564311981201172

Tổng theo chiều dọc của mảng là: [ 13.8027115  -9.312108  -14.054916 ]

Tổng theo chiều ngang của mảng là: [ -0.8886671   2.9121876 -11.587833 ]
