Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 1 chiều?

In [ ]:
import numpy as np
import torch
import tensorflow as tf
# import các thư viện cần dùng 

In [3]:
lst = [1,2,3,4,5,6,7,8,9]
# tạo mảng 1 chiều trước để khởi tạo bằng các cách khác nhau

In [ ]:
np_1D_array = np.array(lst)
print(type(np_1D_array))
# xem danh sách 1 chiều vừa tạo thuộc kiểu nào
print(np_1D_array)
# in kết quả theo đề bài

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [ ]:
torch_1D_array = torch.tensor(lst)
print(type(torch_1D_array))
# xem tensor 1 chiều vừa tạo thuộc kiểu nào
print(torch_1D_array)
# in kết quả theo đề bài

<class 'torch.Tensor'>
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
tensor_1D_array = tf.convert_to_tensor(lst)
print(type(tensor_1D_array))
# xem tensor 1 chiều vừa tạo thuộc kiểu nào 
print(tensor_1D_array)
# in kết quả theo đề bài

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 2 chiều. Sau đó thực hiện kiểm tra thuộc tính shape, dtype, type, device từ các array, tensor vừa tạo ?

In [6]:
lst_2D = [[1,2,3],
          [4,5,6],
          [7,8,9]]
# tạo mảng 2 chiều trước để khởi tạo thành nhiều kiểu khác nhau

In [ ]:
np_2D_array = np.array(lst_2D)
print(f"kích thước của mảng np_2D_array là: {np_2D_array.shape}")
print(f"kiểu dữ liệu của mảng np_2D_array là: {np_2D_array.dtype}")
print(f"kiểu của mảng np_2D_array là: {type(np_2D_array)}")

kích thước của mảng np_2D_array là: (3, 3)
kiểu dữ liệu của mảng np_2D_array là: int64
kiểu của mảng np_2D_array là: <class 'numpy.ndarray'>
thiết bị mà mảng np_2D_array lưu trữ: cpu


In [ ]:
torch_2D_array = torch.tensor(lst_2D)
print(f"kích thước của torch_2D_array là: {torch_2D_array.shape}")
print(f"kiểu dữ liệu của torch_2D_array là: {torch_2D_array.dtype}")
print(f"kiểu của torch_2D_array là: {type(torch_2D_array)}")
print(f"thiết bị mà torch_2D_array lưu trữ: {torch_2D_array.device}")

kích thước của mảng torch_2D_array là: torch.Size([3, 3])
kiểu dữ liệu của mảng torch_2D_array là: torch.int64
kiểu của mảng torch_2D_array là: <class 'torch.Tensor'>
thiết bị mà mảng torch_2D_array lưu trữ: cpu


In [ ]:
tensor_2D_array = tf.convert_to_tensor(lst_2D)
print(f"kích thước của tensor_2D_array là: {tensor_2D_array.shape}")
print(f"kiểu dữ liệu của tensor_2D_array là: {tensor_2D_array.dtype}")
print(f"kiểu của tensor_2D_array là: {type(tensor_2D_array)}")
print(f"thiết bị mà tensor_2D_array lưu trữ: {tensor_2D_array.device}")

kích thước của mảng tensor_2D_array là: (3, 3)
kiểu dữ liệu của mảng tensor_2D_array là: <dtype: 'int32'>
kiểu của mảng tensor_2D_array là: <class 'tensorflow.python.framework.ops.EagerTensor'>
thiết bị mà mảng tensor_2D_array lưu trữ: /job:localhost/replica:0/task:0/device:CPU:0
