In [2]:
import numpy as np 
import torch 
import tensorflow as tf

Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor trong khoảng [0, 10) với step=1?

In [2]:
arr_arange = torch.arange(10)
print(arr_arange)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
arr_arange = tf.range(10)
print(arr_arange)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [4]:
arr_arange = np.arange(10)
print(arr_arange)

[0 1 2 3 4 5 6 7 8 9]


Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor là ma trận đơn vị với kích thước (3, 3).

In [5]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print(tf.eye(3,3))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [7]:
print(torch.eye(3,3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Câu 3: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor ngẫu nhiên trong khoảng giá trị [0, 1] với kích thước (3, 4). Tiếp theo hãy tạo array, tensor với các giá trị là số nguyên trong khoảng [-10, 10]. Lưu ý trong bài tập này, các bạn sẽ sử dụng seed = 2024 để dảm bảo ra kết quả giống đáp án, cách sử dụng như sau:

In [13]:
np.random.seed(2024)
print(np.random.rand(3,4))
print()
print(np.random.randint(-10, 10,size=(3,4)))

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]

[[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [16]:
torch.manual_seed(2024)
print(torch.rand(3,4))
print()
print(torch.randint(-10, 10,size=(3,4)))

tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])

tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [18]:
tf.random.set_seed(2024)
print(tf.random.uniform((3,4)))
print()
print(tf.random.uniform((3,4),minval=-10,maxval =10))

tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)

tf.Tensor(
[[ 1.6345768   5.242193    0.43196487 -4.9151683 ]
 [-3.8236713  -0.25904465 -8.645498   -3.7031531 ]
 [ 2.0925856   5.5088787   7.718027   -7.3018003 ]], shape=(3, 4), dtype=float32)
